# Generated by Django 5.2.7 on 2025-10-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='ask_question_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='online_consultation_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='doctor',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text="Эл аралык форматта, бирок '+' белгиси жок. Мисалы: 996555123456", max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='bio',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
